name: Build and Deploy Module

on:
  workflow_dispatch:
  push:
    branches: [ main , dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: Install dependencies
        run: go mod tidy
      - name: Build project
        run: go build -v ./...
      - name: Publish module
        run: echo "Publishing module to go mod proxy" # Replace with your actual publish command


